# Quantum Forge Activity 2
## This Notebook is for me to learn the basics of Jupyter notebooks and Python
 I am going to learn how to write Python code.
 
 Michael Creager

In [1]:
my_first_variable = "hello world" 

print(my_first_variable)

hello world


In [78]:
import numpy as np

tau = 2*np.pi
print(tau)
tau_str = "\u03C4"

6.283185307179586


In [6]:
string1 = "\u03C4 = {}".format(tau)
string2 = "{}={}.format(tau_str,tau)"
string3 = "{name}={value}".format(name=tau_str,value=tau)
string4 = "{name} is a Greek letter pronounced 'tau' and it represents a full revoltion around " \
"the circle; in radians {name} = {value}".format(name=tau_str, value=tau)
print(f"{tau_str} = {tau:.2f}")

τ = 6.28


In [7]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [9]:
my_first_list = ["this","is","my","first","list"]
print(my_first_list)

['this', 'is', 'my', 'first', 'list']


In [11]:
list_to_fill = [0]*10
print(list_to_fill)
list_to_fill[2] = 55
list_to_fill[7] = 12
print(list_to_fill)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 55, 0, 0, 0, 0, 12, 0, 0]


In [15]:
list_to_loop_over = 'the brown dog jumped over the white fence'.split(' ')
for list_element in list_to_loop_over:
    print(list_element)

the
brown
dog
jumped
over
the
white
fence


In [20]:
list1 = [1,2,3]
list2 = ['a','b','c'] 
for el1, el2 in zip(list1,list2):
    print(f'{el1}::{el2}')
    
print(zip(list1,list2))
print(tuple(zip(list1,list2)))

1::a
2::b
3::c
((1, 'a'), (2, 'b'), (3, 'c'))


In [17]:
for el1 in list1:
    for el2 in list2:
        print(f'{el1}::{el2}')
    

1::a
1::b
1::c
2::a
2::b
2::c
3::a
3::b
3::c


In [22]:
my_array = np.array([[1,2,3],[2,3,1]])
print(my_array.shape)

(2, 3)


In [32]:
x = np.arange(5)
y = np.array([[4],[2],[3],[1]])
print(x*x,x*y,y*y,x+x,x+y,y+y)

[ 0  1  4  9 16] [[ 0  4  8 12 16]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  1  2  3  4]] [[16]
 [ 4]
 [ 9]
 [ 1]] [0 2 4 6 8] [[4 5 6 7 8]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [1 2 3 4 5]] [[8]
 [4]
 [6]
 [2]]


In [34]:
x = np.array([1,3,4])
y = np.array([2,9,1])
sum(x*y)

33

In [40]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,3],[2,1]])
print(a,b)
c = np.dot(a,b)
print(c)

[[1 2]
 [3 4]] [[4 3]
 [2 1]]
[[ 8  5]
 [20 13]]


# Exercises
## Question 1

### A

In [49]:
t = [1,2,3,6]
pi = np.pi

for ii in [1,2,3,6]:
    print(pi/ii)





3.141592653589793
1.5707963267948966
1.0471975511965976
0.5235987755982988


### B

I didn't really have time to figure this out 

### C

In [61]:
k = -21
f = [1]*11
for jj in f:
    k = k +1
    print(k)

-20
-19
-18
-17
-16
-15
-14
-13
-12
-11
-10


### D

In [68]:
d = [0,1,1,2,3,5,8,13,21,34]
f = [0,1,2,3,4,5,6,7,8,9]
for kk in f:
    print(d[kk])
        

0
1
1
2
3
5
8
13
21
34


## Question 2

In [47]:
num=4256687749
z = str(num)
print(len(z))

10
